export const gujaratDistricts = [
  "Ahmedabad",
  "Amreli",
  "Anand",
  "Aravalli",
  "Banaskantha",
  "Bharuch",
  "Bhavnagar",
  "Botad",
  "Chhota Udaipur",
  "Dahod",
  "Dang",
  "Devbhoomi Dwarka",
  "Gandhinagar",
  "Gir Somnath",
  "Jamnagar",
  "Junagadh",
  "Kheda",
  "Kutch",
  "Mahisagar",
  "Mehsana",
  "Morbi",
  "Narmada",
  "Navsari",
  "Panchmahal",
  "Patan",
  "Porbandar",
  "Rajkot",
  "Sabarkantha",
  "Surat",
  "Surendranagar",
  "Tapi",
  "Vadodara",
  "Valsad",
]

export const gujaratCities: Record<string, string[]> = {
  Ahmedabad: ["Ahmedabad", "Sanand", "Dholka", "Bavla", "Dhandhuka"],
  Amreli: ["Amreli", "Savarkundla", "Rajula", "Liliya", "Dhari"],
  Anand: ["Anand", "Khambhat", "Petlad", "Borsad", "Sojitra"],
  Aravalli: ["Modasa", "Bhiloda", "Malpur", "Meghraj", "Dhansura"],
  Banaskantha: ["Palanpur", "Deesa", "Dhanera", "Tharad", "Danta"],
  Bharuch: ["Bharuch", "Ankleshwar", "Jambusar", "Vagra", "Amod"],
  Bhavnagar: ["Bhavnagar", "Sihor", "Palitana", "Talaja", "Mahuva"],
  Botad: ["Botad", "Gadhada", "Barwala", "Ranpur"],
  "Chhota Udaipur": ["Chhota Udaipur", "Kavant", "Naswadi", "Bodeli"],
  Dahod: ["Dahod", "Jhalod", "Limkheda", "Garbada", "Devgadh Baria"],
  Dang: ["Ahwa", "Waghai", "Subir"],
  "Devbhoomi Dwarka": ["Khambhalia", "Dwarka", "Kalyanpur", "Bhanvad"],
  Gandhinagar: ["Gandhinagar", "Kalol", "Dehgam", "Mansa"],
  "Gir Somnath": ["Veraval", "Somnath", "Kodinar", "Una", "Sutrapada"],
  Jamnagar: ["Jamnagar", "Kalavad", "Dhrol", "Jamjodhpur", "Jodiya"],
  Junagadh: ["Junagadh", "Visavadar", "Mangrol", "Manavadar", "Keshod"],
  Kheda: ["Nadiad", "Kheda", "Kapadvanj", "Balasinor", "Mahudha"],
  Kutch: ["Bhuj", "Anjar", "Gandhidham", "Mandvi", "Naliya"],
  Mahisagar: ["Lunawada", "Santrampur", "Kadana", "Balasinor"],
  Mehsana: ["Mehsana", "Visnagar", "Kadi", "Jotana", "Unjha"],
  Morbi: ["Morbi", "Wankaner", "Halvad", "Tankara", "Maliya"],
  Narmada: ["Rajpipla", "Nandod", "Tilakwada", "Dediapada"],
  Navsari: ["Navsari", "Vansda", "Chikhli", "Gandevi", "Jalalpore"],
  Panchmahal: ["Godhra", "Kalol", "Halol", "Jambughoda", "Shahera"],
  Patan: ["Patan", "Sidhpur", "Chanasma", "Harij", "Radhanpur"],
  Porbandar: ["Porbandar", "Ranavav", "Kutiyana"],
  Rajkot: ["Rajkot", "Gondal", "Jetpur", "Dhoraji", "Upleta"],
  Sabarkantha: ["Himmatnagar", "Prantij", "Talod", "Khedbrahma", "Idar"],
  Surat: ["Surat", "Bardoli", "Mandvi", "Mahuva", "Vyara"],
  Surendranagar: ["Surendranagar", "Wadhwan", "Limbdi", "Chotila", "Dhrangadhra"],
  Tapi: ["Vyara", "Songadh", "Uchchhal", "Nizar", "Valod"],
  Vadodara: ["Vadodara", "Dabhoi", "Padra", "Karjan", "Savli"],
  Valsad: ["Valsad", "Pardi", "Vapi", "Dharampur", "Kaprada"],
}
